export const ELEMENTS = {

    carrouselhome               : '#slider-carousel > .carousel-inner > .active > :nth-child(1)',
    btnSignupLogin              : '.shop-menu > .nav > :nth-child(4) > a'                       ,
    formSignupLogin             : '#form > .container > .row'                                   ,
    fieldLoginEmail             : '[data-qa="login-email"]'                                     ,
    fieldLoginPasswd            : '[data-qa="login-password"]'                                  ,
    btnLogin                    : '[data-qa="login-button"]'                                    ,
    fieldMsgSignup              : '.login-form > form > p'                                      ,
    fieldSignupName             : '[data-qa="signup-name"]'                                     ,
    fieldSignupEmail            : '[data-qa="signup-email"]'                                    ,
    btnSignup                   : '[data-qa="signup-button"]'                                   ,
    rdbGenderMasc               : '#id_gender1'                                                 ,
    fieldFormNameSignup         : '[data-qa="name"]'                                            ,
    fieldFormPasswordSignup     : '[data-qa="password"]'                                        ,
    fieldFormDayBirthSignup     : '[data-qa="days"]'                                            ,
    fieldFormMonthBirthSignup   : '[data-qa="months"]'                                          ,
    fieldFormYearBirthSignup    : '[data-qa="years"]'                                           ,
    fieldFormNewsletterSignup   : '#newsletter'                                                 ,
    fieldFormOptionSignup       : '#optin'                                                      ,
    fieldFormFirstName          : '[data-qa="first_name"]'                                      ,
    fieldFormLastName           : '[data-qa="last_name"]'                                       ,
    fieldFormCompany            : '[data-qa="company"]'                                         ,
    fieldFormAddress            : '[data-qa="address"]'                                         ,
    fieldFormAddress2           : '[data-qa="address2"]'                                        ,
    fieldFormCountry            : '[data-qa="country"]'                                         ,
    fieldFormState              : '[data-qa="state"]'                                           ,
    fieldFormCity               : '[data-qa="city"]'                                            ,
    fieldFormZipcode            : '[data-qa="zipcode"]'                                         ,
    fieldFormMobileNumber       : '[data-qa="mobile_number"]'                                   ,
    btnCreateAccount            : '[data-qa="create-account"]'                                  ,
    msgActionAccount            : 'b'                                                           ,
    btnContinue                 : '[data-qa="continue-button"]'                                 ,
    btnLogout                   : '.shop-menu > .nav > :nth-child(4) > a'                       ,
    avatarLogged                : ':nth-child(10) > a'                                          ,
    btnDeleteAccount            : '.shop-menu > .nav > :nth-child(5) > a'                       ,
    fieldMsgExistEmail          : '.signup-form > form > p'                                     ,
    fieldFormNameContact        : '[data-qa="name"]'                                            ,
    fieldFormEmailContact       : '[data-qa="email"]'                                           ,
    fieldFormSubjectContact     : '[data-qa="subject"]'                                         ,
    fieldFormMensageContact     : '[data-qa="message"]'                                         ,
    fieldAtachment              : ':nth-child(6) > .form-control'
}