export const ELEMENTS = {
    btnProducts             : '.shop-menu > .nav > :nth-child(2) > a'                                           ,
    btnFirstAddToCart       : ':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn' ,
    btnSecondAddToCart      : ':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn' ,
    btnViewProduct          : ':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a'                ,
    btnSeachProduct         : '#submit_search'                                                                  ,
    btnModalContinueShopping: '.modal-footer > .btn'                                                            ,
    fieldSearchProduct      : '#search_product'                                                                 ,
    fieldnNameProduct       : ':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > p'    ,
    fieldQuantityBlueTop    : '#product-1 > .cart_quantity > .disabled'                                         ,                                      
    fieldQuantityMenTshirt  : '#product-2 > .cart_quantity > .disabled'                                         ,
    txtAllProducts          : '.title'                                                                          ,
    txtProductName          : '.product-information > h2'                                                       ,
    txtProductCategory      : '.product-information > :nth-child(3)'                                            ,
    txtProductPrice         : ':nth-child(5) > span'                                                            ,
    txtProductAvailability  : '.product-information > :nth-child(6)'                                            ,
    txtProductCondition     : '.product-information > :nth-child(7)'                                            ,
    txtProductBrand         : '.product-information > :nth-child(8)'                                            ,
    txtProductBlueTop       : '#product-1 > .cart_description > h4 > a'                                         ,
    txtPriceTotalBlueTop    : '#product-1 > .cart_total > .cart_total_price'                                    ,
    txtProductMenTshirt     : '#product-2 > .cart_description > h4 > a'                                         ,
    txtPriceTotalMenTshirt  : '#product-2 > .cart_total > .cart_total_price'                                    ,
    msgSeachedProducts      : '.title'                                                                          ,
    buttonAddToCart         : ':nth-child(5) > .btn'                                                            ,
    fieldQuantity           : '#quantity'               
}